version: '3.8'

services:
  backend:
    image: python:3.9
    volumes:
      - ./backend:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --reload"
    ports:
      - "8000:8000"

  frontend:
    image: node:21
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npm install -g @angular/cli && ng serve --host 0.0.0.0 --port 4200"
    ports:
      - "4200:4200"
