"""app_config

Revision ID: 311aef40c7fa
Revises: 
Create Date: 2023-11-11 14:13:41.554214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311aef40c7fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_sources', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('industries', sa.String(), nullable=True),
    sa.Column('ai_model_endpoint', sa.String(), nullable=True),
    sa.Column('ai_model_version', sa.String(), nullable=True),
    sa.Column('ai_model_api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_config_id'), 'app_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_config_id'), table_name='app_config')
    op.drop_table('app_config')
    # ### end Alembic commands ###
