"""data_points

Revision ID: aabd53770b43
Revises: 311aef40c7fa
Create Date: 2023-11-11 16:34:27.645582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabd53770b43'
down_revision: Union[str, None] = '311aef40c7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('most_relevant_keyword', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_points_article_id'), 'data_points', ['article_id'], unique=False)
    op.create_index(op.f('ix_data_points_id'), 'data_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_points_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_article_id'), table_name='data_points')
    op.drop_table('data_points')
    # ### end Alembic commands ###
